name: nlp-autograder
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pandas
  - pytorch
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - docopt
  - nltk
  - torchvision
  - pip
  - transformers
  - pip:
    - sentencepiece
    - sacrebleu
    - tensorboard
    - datasets
    - phonemizer
    - librosa
    - soundfile
